model:
  model_path: "../data/processed/lgb_baseline_model.txt"
  joblib_path: "../data/processed/lgb_baseline_model.joblib"
  encoders_path: "../models/label_encoders.joblib"
  expected_features: ["hour_sin","hour_cos","weekday_sin","weekday_cos","LATITUDE","LONGITUDE","sev_1h","sev_6h","sev_24h","tot_1h","tot_6h","tot_24h","seg_te","cluster_te"]

history:
  dir: "../data/processed/segment_history_files_shifted_v2"
  compute_on_missing: true    

api:
  default_top_k: 10
  max_batch_size: 1000
  cache_ttl_seconds: 300
  allow_anonymous: false