name: roadguardianai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - lightgbm
  - jupyter
  - ipykernel
  - pip:
      - fastapi
      - uvicorn[standard]
      - torch
      - torchvision
      - psycopg2-binary
      - sqlalchemy
      - alembic
      - celery
      - redis
      - prometheus-client
      - shap
      - pytest
      - pydantic
      - python-dotenv
      - requests
      - matplotlib
      - seaborn
