[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "roadguardianai"
version = "0.0.1"
authors = [{name = "Tristan"}]
description = "Real time Road Segment Accident Risk Prediction"
dependencies = []
