model:
  model_path: "C:/Users/trist/Desktop/RoadGuardianAI/models/lgb_baseline_model.txt"
  joblib_path: "C:/Users/trist/Desktop/RoadGuardianAI/models/lgb_baseline_model.joblib"
  encoders_path: "C:/Users/trist/Desktop/RoadGuardianAI/models/label_encoders.joblib"
  expected_features:
    - hour_sin
    - hour_cos
    - weekday_sin
    - weekday_cos
    - LATITUDE
    - LONGITUDE
    - sev_1h
    - sev_6h
    - sev_24h
    - tot_1h
    - tot_6h
    - tot_24h
    - seg_te
    - cluster_te

history:
  dir: "C:/Users/trist/Desktop/RoadGuardianAI/data/processed/segment_history_files_shifted_v2"

api:
  default_top_k: 10
  cache_ttl_seconds: 300
  batch_size: 2000
